---
title: "36-315 Homework 01, Spring 2016"
author: "Your Name Here"
date: "Due Wednesday, January 20, 2016 (12pm ET) on Blackboard"
output: html_document
---

#  Homework 01:  Introduction to R, RStudio, Data Types, and Critiquing Graphics

***General instructions for homeworks***: 

+  Upload an R Markdown file (named as:  [AndrewID]-[HW01].Rmd -- e.g. "sventura-HW01.Rmd") to Blackboard in the Homework 01 submission section on Blackboard
+  Your file should contain the code/commands to answer each question in its own code block, which will also produce plots that will be automatically embedded in the output file
+  Each answer must be supported by written statements (unless otherwise specified) as well
+  Include the name of anyone you collaborated with at the top of the assignment
+  For Homework 01 only, do not worry about adhering to a particular style guide.  We will cover this next week.


#  Problem 1

(10 points)

**Downloading R and R Studio**:  

If you are using your own, personal computer, you will need to download and install R and RStudio.  Follow the instructions here to do so (be sure to choose the correct operating system, and 64-bit R if possible/compatible):  [https://www.rstudio.com/products/rstudio/download/]

Once you get RStudio open, download the Homework01.Rmd file from Blackboard and open it in RStudio (File / Open...).  It may be helpful to use the Lab01.Rmd file on Blackboard as a template for your submission.  Feel free to do so.  If you do, be sure to delete all of the problem statements and additional text, as these are not necessary to include in your submission.

Notice how the text you write in the .Rmd file shows up in the output file each time you click "Knit HTML".  

For more tips/tricks on how to format things in R Markdown, go to [https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf]

**Customizing the RStudio User Interface**:

The first thing you'll notice is that, in the RStudio window, there are several panes that contain various things (Console, Help, Environment, History, Plots, etc).

If you're using Mac, go to RStudio / Preferences / Pane Layout.  If you're using Windows, go to Tools / Global Options.  Change the menu options to arrange the panes as you see fit.  

**In your answer to this problem**, describe your chosen Pane Layout and give a brief explanation for why you chose this.

Personally, I prefer to have:

+  Source in its own pane on the top-right-hand side
+  Console in it's own pane on the top-left-hand side of the window
+  Help and Git on the bottom-right
+  Everything else on the bottom-left

Click Apply.  Now click Appearance and choose an appropriate font, font size, and theme.  I personally prefer a fixed-width font like Courier.

Click Apply and Okay.  Finally, when coding, I prefer to minimize the bottom-left and bottom-right panes so that I have more vertical space to see the code I'm writing and the output it's generating.


**Where is my output file?**

Find where you stored your [AndrewID]-HW01.Rmd file on your computer.  

In the same directory, there should be a file called [AndrewID]-HW01.html.  

Open it.  It should automatically open in a browser, and it should contain the output.  

In the future, you'll submit these .html files along with your .Rmd files for homeworks and labs.


#  Problem 2

(20 points)

**Critiquing Graphs**:

Find a graph from the internet, preferably something that was in a recent (last 7 days) news article, blog post, etc.  Describe and crique your graph:

+  What does the graph show?
+  Does the graph do a good job of achieving its goals?
+  Does the graph use an unnecessary amount of data ink?
+  What are the strong points (advantages) of the graphic?
+  What are the weak points (disadvantages) of the graphic?
+  What would you change (if anything) about this graphic?
+  Read the caption and/or surrounding text.  Does the text enhance the user's understanding of the graphic?


#  Problem 3

**Writing R Functions and Working with Vectors**:  

Read section 5 of Wasserman's R Intro document on Blackboard about writing functions in R.  Functions help us reuse code and enhance the reproduciblity of our code.

a.  (5 points)  Write an R function called `quadratic` that computes the quadratic formula.  That is, write a function that has four inputs -- ```a```, ```b```, ```c```, and ```x``` and returns the quantity $ax^2 + bx + c$.

b.  (2 points)  Test your function out and demonstrate that it works for at least there different combinations of the parameters.

c.  (2 points)  Type `quadratic(x=2)` into your code block.  What happens when you only specify one argument?

c.  (2 points)  Create a new function, `quadratic2`, that has default values for ```a=1```, ```b=1```, and ```c=1```.  Type `quadratic2(x=2)` into your code block.  What happens when you only specify one argument?

d.  (2 points)  Type `1:10` at the command line in R.  What happens?  

e.  (2 points)  What happens when you call the function with the following input:  `quadratic2(x = 1:10)`.  Why does this happen?

f.  (5 points)  Type `plot(1:10, quadratic2(x=1:10))` into your code block.  Describe the graph that shows up.


#  Problem 4

**Introduction to ggplot2**:  

In R, there are several libraries or packages/groups of programs that are not used enough to have them permanently stored in R.  One that will be particularly useful in our class is called `ggplot2`.

a.  (2 points)  Type `library(ggplot2)` at the command line.  Is the `ggplot2` package installed on your computer?  If not, type `install.packages("ggplot2")`, then repeat the `library(ggplot2)` command above.

b.  (2 points)  The Comprehensive R Archive Network, or CRAN, stores most publicly accessible, open-source R packages for anyone to use.  Find CRAN's documentation on the `ggplot2` package (e.g. by searching "ggplot2 in R" on the internet).  You should find a PDF document that has 198 pages of documentation about `ggplot2`.  What does the "gg" in `ggplot2` stand for?

c.  (2 points)  Who are the authors of the `ggplot2` package?  Who is the maintainer of the `ggplot2` package?  Search this person's name on the internet.  What are some other R packages this person has written?

d.  (2 points)  Type `library(datasets)`. Load the `trees` dataset into R by typing `data(trees)`.  Type `head(trees)` to view the first few rows of this dataset.  How many columns does the dataset have?  What are the names of the columns?

e.  (12 points)  Make your first `ggplot2` graphic:  

    +  Type `my.plot <- ggplot(data = trees, aes(x = Girth, y = Height))`.  This will create the graph object.
    +  Type `my.plot <- my.plot + geom_point(data = trees, aes(colour = Volume), size = 4)`.  This will add points to the graph object, colored by Volume.
    +  Type `my.plot <- my.plot + ggtitle("Title Here") + labs(x = "x axis label here", y = "y axis label here")`
    +  Change the above code to give the graph an informative title and informative axis labels.  Include units in the axis labels if possible.  See `help(trees)` for more information about the units.
    +  Critique your own graph.  What do you like?  What do you dislike?  What would you change in the future?
    +  Is there any unnecessary data ink used in this graph?


#  Problem 5

**Cornell Tuition**:  

Read the Cornell Tuition document (cornell.pdf) in the Homework 01 section on Blackboard.  

a.  (5 points)  What are the main issues outlined by the author in the document?  
b.  (5 points)  What would you change about the graph?


#  Problem 6

**The Shrinking Doctor**:  

Download the Incredible Shrinking Doctor graphic from the Homework 01 section on Blackboard. 

a.  (2 points)  Use the distortion and design variation principles discussed in class to critique this graphic.  

b.  (2 points)  What are the actual data quantities being visualized?

c.  (6 points)  Calculate the Lie Factors for 1975 and 1990, relative to the baseline of 1964, by comparing the
change in area of the graphics to the change in the fraction of family practice doctors.  You might need a ruler to do this!


#  Problem 7
(5 points)

**Discussion Board**:

Go to the discussion board on Blackboard.  Subscribe to all of the threads currently available.  No need to write a solution here -- we trust that you will actually do this, since you will be at a disadvantage for the rest of the semester otherwise.


#  Problem 8
(5 points)

**Consent to Use Lab Solutions**:

If you do very well on a lab, we would like to post your solutions for that lab assignment to Blackboard for other students to see.  Posted solutions will, of course, be anonymized, so that other students will not know that the solutions are yours.  We will not post homework or lab exam solutions to Blackboard.

You are welcome to opt out of this if you want to.  Just answer the following question:  Do you consent to having your (anonymized) lab solutions posted to Blackboard?

(You will receive 5 points regardless of what you answer -- we just need to know ahead of time!)

